name: task_management
description: "A new Flutter project."
publish_to: 'none'   
version: 1.0.0+5

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences:  
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2 
  dropdown_button2: ^2.3.9
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  # flutter_background_service: ^5.0.10
  # flutter_background_service_android: ^6.2.7
  # flutter_background_service_ios: ^5.0.3
  syncfusion_flutter_calendar: ^30.1.39 
  percent_indicator: ^4.2.4
  linear_progress_bar: ^1.1.2
  google_nav_bar: ^5.0.7
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer:  
  path: 
  intl: ^0.19.0
  permission_handler: ^11.3.1
  location: ^8.0.0
  google_maps_flutter: ^2.5.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  app_settings: ^5.1.1
  calendar_view: ^1.3.0
  data_table_2: ^2.5.18
  badges: ^3.1.2
  pdf: ^3.11.1
  readmore: 
  pusher_channels_flutter:  
  multi_dropdown: ^3.0.1
  flutter_searchable_dropdown: ^2.0.0
  sqflite: 
  dropdown_search: ^6.0.2
  persistent_bottom_nav_bar_v2: ^5.3.1
  file_picker: 
  camera: ^0.10.5+5
  dotted_border: ^2.1.0 
  animated_segmented_tab_control: ^2.0.0
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  floating_action_bubble: ^1.1.4
  file_saver: ^0.2.14
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^11.4.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  geocoding_platform_interface: any
  timezone: any
  http: any
  flutter_datetime_picker_plus: ^2.2.0
  google_sign_in: ^6.3.0
  googleapis:  
  googleapis_auth: 
  dart_quill_delta: ^10.8.3 
  cached_network_image: any
  crypto: any
  device_info_plus: any
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  emoji_picker_flutter: ^4.3.0
  screenshot: ^3.0.0
  record: ^6.0.0
  flutter_cache_manager: ^3.4.1
  audioplayers: ^6.5.0
  swipe_to: ^1.0.6
  media_store_plus: ^0.1.3
  in_app_update: ^4.2.3
  open_file: ^3.5.10
  # background_locator_2:
  # background_locator_2:
  #   git:
  #     url: https://github.com/sultan18kh/background_locator_2_gradle_migration.git
  #     ref: fix/gradle-compatibility  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true  
  image_path: "assets/image/png/winntusapplogo.jpg" 
  min_sdk_android: 21
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
    - assets/gif/
    - assets/task_images/
    - assets/mp3/alarm.mp3
    - assets/mp3/notificationtone.mp3
    - assets/mp3/alarmsound.mp3
    - assets/mp3/emergency_alarm_69780.mp3
    - assets/image/svg/
    - assets/image/png/
